# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolodet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.lblimg = QtWidgets.QLabel(MainWindow)
        self.lblimg.setGeometry(QtCore.QRect(30, 20, 321, 221))
        self.lblimg.setText("")
        self.lblimg.setObjectName("lblimg")
        self.btnopen = QtWidgets.QPushButton(MainWindow)
        self.btnopen.setGeometry(QtCore.QRect(150, 260, 75, 23))
        self.btnopen.setObjectName("btnopen")

        self.textedit = QtWidgets.QLineEdit(MainWindow)
        self.textedit.setGeometry(QtCore.QRect(150, 300, 75, 23))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.btnopen.setText(_translate("MainWindow", "打开"))
